import os
import re

source_file = "src/app/treatments/root-canal/page.tsx"
with open(source_file, "r") as f:
    template = f.read()

treatments = [
    {
        "id": "braces-and-aligners",
        "component_name": "BracesAndAligners",
        "breadcrumb": "Braces & Aligners",
        "hero_badge": "Advanced Orthodontics",
        "hero_title": "Invisible Aligners & Advanced Orthodontics",
        "hero_desc": "Achieve a perfectly straight, healthy smile with our advanced clear aligner systems or low-profile ceramic brackets, personalized for your unique bite.",
        "m1_v": "12-18m", "m1_l": "Avg Duration",
        "m2_v": "0%", "m2_l": "Discomfort",
        "m3_v": "100%", "m3_l": "Custom Fit",
        "m4_v": "5k+", "m4_l": "Smiles Aligned",
        "cta": "Schedule Alignment Consultation",
        "b1": "3D Intraoral Scanning", "b2": "Clear Aligner Tech", "b3": "Invisible Aesthetics",
        "image_url": "https://lh3.googleusercontent.com/aida/AEtjO1U3wB9Fw7tJ2qY-ZpG0d9lM6a5jX2_kLk3_9v3H7l1gP5kX3sY7r9N-w0Q6a4l1p8mK4sP3e5oQ1m7_t8w8vK5k9bN4g-s8d6",
        "img_title": "Digital Smile Simulation", "img_sub": "Predictable Outcomes", "img_desc": "See your future smile before treatment even begins with our advanced 3D scanning technology.",
        "mini_title": "Discreet & Comfortable", "mini_desc": "No metal wires or brackets",
        "s2_label": "ALIGNMENT SCIENCE",
        "s2_title": "Understanding Orthodontic Realignment",
        "s2_d1": "Orthodontic treatment goes beyond aesthetics; it corrects bite mechanics, improves oral hygiene, and prevents jaw strain.",
        "s2_d2": "Using continuous, gentle pressure, braces or clear aligners slowly shift teeth into their optimal positions. This process remodels the surrounding jawbone, ensuring long-lasting stability.",
        "s2_h_title": "Health vs. Aesthetics",
        "s2_h_desc": "Straight teeth are easier to clean, reducing the risk of decay and gum disease while giving you a confident, beautiful smile.",
        "sym_label": "Assessment", "sym_title": "Signs You Might Need Orthodontics",
        "sym1_t": "Crowding", "sym1_d": "Teeth overlapping or bunched together, making it difficult to brush and floss properly.",
        "sym2_t": "Spacing", "sym2_d": "Visible gaps between teeth which can trap food and cause gum inflammation.",
        "sym3_t": "Overbite", "sym3_d": "Upper front teeth excessively overlap the lower front teeth.",
        "sym4_t": "Underbite", "sym4_d": "Lower front teeth protrude past the upper front teeth.",
        "sym5_t": "Crossbite", "sym5_d": "Upper and lower jaws are misaligned when biting together.",
        "tech_label": "Digital Orthodontics", "tech_title": "Next-Generation Alignment Technology", "tech_desc": "We utilize advanced 3D scanning and computer-aided treatment planning to ensure predictable, efficient, and comfortable tooth movement.",
        "t1_t": "3D Intraoral Scanners", "t1_d": "Eliminates messy traditional putty impressions, providing a highly accurate digital model of your teeth.", "t1_m": "No Gag Reflex",
        "t2_t": "Digital Treatment Simulation", "t2_d": "Advanced software maps out the exact movement of your teeth at every stage of the treatment.", "t2_m": "Predictable Results",
        "t3_t": "SmartTrack Materials", "t3_d": "Highly elastic materials deliver gentle, constant force to move teeth comfortably and efficiently.", "t3_m": "Faster Alignment",
        "t4_t": "Custom Attachments", "t4_d": "Tiny, tooth-colored grips are placed on specific teeth to facilitate complex movements with aligners.", "t4_m": "Precision Control",
        "ban_t": "Are Clear Aligners Right For You?", "ban_d": "Most cases can be treated with invisible aligners, offering a discreet and removable alternative to traditional metal braces.", "ban_c": "Check Aligner Eligibility",
        "step_l": "Treatment Protocol", "step_t": "The Orthodontic Journey", "step_d": "Experience a seamless path to your new smile with our structured, digitally-guided process.",
        "st1_t": "Consultation & 3D Scan", "st1_d": "Comprehensive evaluation of your bite and digital impression of your teeth.",
        "st2_t": "Treatment Planning", "st2_d": "Computer simulation of your tooth movements and timeline estimation.",
        "st3_t": "Appliance Delivery", "st3_d": "Fitting of your custom aligners or low-profile brackets.",
        "st4_t": "Progress Monitoring", "st4_d": "Regular check-ups to track your alignment and make necessary adjustments.",
        "st5_t": "Retention Phase", "st5_d": "Custom retainers provided to maintain your new smile forever.",
        "ft_t": "Lifetime Smile Guarantee", "ft_d": "Our retention program ensures your teeth stay perfectly aligned."
    },
    {
        "id": "crowns-and-bridges",
        "component_name": "CrownsAndBridges",
        "breadcrumb": "Crowns & Bridges",
        "hero_badge": "Restorative Dentistry",
        "hero_title": "Precision-Milled Crowns & Bridges",
        "hero_desc": "Restore damaged or missing teeth with CAD/CAM precision-milled monolithic zirconia and IPS E-Max porcelain for lasting durability and natural aesthetics.",
        "m1_v": "10-15y", "m1_l": "Average Lifespan",
        "m2_v": "100%", "m2_l": "Custom Matched",
        "m3_v": "0", "m3_l": "Metal Used",
        "m4_v": "10k+", "m4_l": "Restorations",
        "cta": "Schedule Restorative Visit",
        "b1": "CAD/CAM Precision", "b2": "Zirconia & E-Max", "b3": "Metal-Free",
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuC00_ao04m5y2ZZyDF6KTmlvOdr3wYaoxuaw2dTd7ovrS-FIL5fCtViMLFzwsTNgPwl5UQHXOmonyoLk1PSaSspHY-AhrcxmLiFfXEJewr8STw1TwXTTtFCLQOG6x4RMEnTbwbFq5weSthzzZ4UBH0h_CS87r1Uo8FOEIMyDdqNoIa3gWGOvxbJLsR-nO-G9_ShbqWfvSYVAt97yQzMg096mD0evGPWynoj9DIcXtidKbQhJzVrWfIYyw",
        "img_title": "Digital Milling Technology", "img_sub": "Micron-Level Accuracy", "img_desc": "Our crowns are digitally designed and milled to fit your tooth preparation perfectly.",
        "mini_title": "Natural Appearance", "mini_desc": "Shade-matched to your existing teeth",
        "s2_label": "RESTORATIVE SCIENCE",
        "s2_title": "Understanding Structural Restoration",
        "s2_d1": "When a tooth is severely weakened by decay, trauma, or root canal therapy, a filling is no longer sufficient to withstand chewing forces.",
        "s2_d2": "Crowns encase the entire visible portion of the tooth, providing structural integrity. Bridges utilize adjacent healthy teeth to support a suspended replacement tooth, closing gaps permanently.",
        "s2_h_title": "Function & Protection",
        "s2_h_desc": "Beyond aesthetics, crowns prevent weakened teeth from fracturing, while bridges stop adjacent teeth from drifting into empty spaces.",
        "sym_label": "Assessment", "sym_title": "When Are Crowns & Bridges Needed?",
        "sym1_t": "Severe Decay", "sym1_d": "Cavities too large to be supported by a traditional filling.",
        "sym2_t": "Cracked Teeth", "sym2_d": "Visible fractures or pain when chewing, indicating a compromised tooth structure.",
        "sym3_t": "Post-Root Canal", "sym3_d": "Teeth become brittle after nerve removal and require a crown for protection.",
        "sym4_t": "Missing Teeth", "sym4_d": "One or more missing teeth that need a fixed replacement without surgery.",
        "sym5_t": "Cosmetic Irregularities", "sym5_d": "Severely discolored, misshapen, or worn down teeth requiring full coverage.",
        "tech_label": "Digital Restorations", "tech_title": "Advanced Restorative Technology", "tech_desc": "We employ the latest materials and digital workflows to deliver crowns and bridges that look and function exactly like natural teeth.",
        "t1_t": "Intraoral Optical Scanning", "t1_d": "No gooey impressions. We capture a highly accurate 3D map of your prepared teeth.", "t1_m": "Comfortable & Fast",
        "t2_t": "CAD/CAM Design", "t2_d": "Your restoration is designed digitally to ensure perfect bite occlusion and contact points.", "t2_m": "Micron Precision",
        "t3_t": "Monolithic Zirconia", "t3_d": "Extremely durable, metal-free material ideal for molars enduring high chewing forces.", "t3_m": "Maximum Strength",
        "t4_t": "IPS E-Max Porcelain", "t4_d": "Highly translucent lithium disilicate ceramic that mimics natural enamel perfectly for front teeth.", "t4_m": "Superior Aesthetics",
        "ban_t": "Tired of Uncomfortable Gaps?", "ban_d": "A well-crafted dental bridge can restore your chewing ability and confidence in just a few visits.", "ban_c": "Explore Bridge Options",
        "step_l": "Treatment Protocol", "step_t": "The Restorative Journey", "step_d": "A streamlined process to restore your tooth's form and function.",
        "st1_t": "Preparation", "st1_d": "Gentle reshaping of the tooth under local anesthesia.",
        "st2_t": "Digital Impression", "st2_d": "A quick 3D scan is taken of the prepared tooth.",
        "st3_t": "Temporary Restoration", "st3_d": "A provisional crown is placed to protect the tooth while the final is made.",
        "st4_t": "Fabrication", "st4_d": "Your custom crown is milled and shade-matched in the lab.",
        "st5_t": "Final Cementation", "st5_d": "The permanent restoration is bonded securely into place.",
        "ft_t": "Lasting Durability Guarantee", "ft_d": "Our premium materials ensure your restoration withstands the test of time."
    },
    {
        "id": "teeth-cleaning-and-scaling",
        "component_name": "TeethCleaningAndScaling",
        "breadcrumb": "Teeth Cleaning & Scaling",
        "hero_badge": "Preventive Care",
        "hero_title": "Professional Teeth Cleaning & Scaling",
        "hero_desc": "Protect your gums against gingivitis and eliminate bad breath with gentle piezo-ultrasonic tartar removal and deep subgingival curettage.",
        "m1_v": "6m", "m1_l": "Rec. Frequency",
        "m2_v": "100%", "m2_l": "Plaque Removal",
        "m3_v": "0%", "m3_l": "Enamel Damage",
        "m4_v": "20k+", "m4_l": "Cleanings Performed",
        "cta": "Book Your Cleaning Session",
        "b1": "Ultrasonic Scaling", "b2": "Stain Removal", "b3": "Gum Health",
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuDA3mV3uj2m0Z4vg6P2mUecAuuvR3f6UO3a-Eu9wGnGfmhB-RvlRzoGdbMqjgHy3Um-zX_f5OTPM5E6Dyf39CODpG1I9b7xZuXj8BeNatLgFj0zCxkX55QUvp3lRg-GqZaLeGF5U40uwBt943qNiu8iRL1UvdMa1ERAFZJFD3TDc3CvEfHCzY4LAbiNMHoKBODxgV8O43bTR4x09DKKWpCJizvFBukNGVonNe623BumbA_RBOF85Nsttw",
        "img_title": "Piezo-Ultrasonic Technology", "img_sub": "Gentle & Effective", "img_desc": "High-frequency vibrations gently shatter stubborn calculus without scraping.",
        "mini_title": "Fresh Breath", "mini_desc": "Eliminates odor-causing bacteria",
        "s2_label": "PREVENTIVE SCIENCE",
        "s2_title": "Understanding Calculus & Gum Disease",
        "s2_d1": "Even with diligent brushing, plaque—a sticky film of bacteria—can harden into calculus (tartar) in hard-to-reach areas.",
        "s2_d2": "Once tartar forms, it cannot be removed with a toothbrush. If left untreated, it irritates the gums, leading to gingivitis and eventually periodontitis, which causes bone loss and tooth mobility.",
        "s2_h_title": "Prevention is Better than Cure",
        "s2_h_desc": "Routine scaling removes these harmful deposits, preventing the progression of gum disease and systemic health issues linked to oral bacteria.",
        "sym_label": "Assessment", "sym_title": "Signs You Need Professional Cleaning",
        "sym1_t": "Bleeding Gums", "sym1_d": "Gums that bleed easily when brushing or flossing.",
        "sym2_t": "Bad Breath", "sym2_d": "Persistent halitosis or a bad taste in your mouth that won't go away.",
        "sym3_t": "Visible Tartar", "sym3_d": "Yellow or brown hard deposits along the gumline, especially on the lower front teeth.",
        "sym4_t": "Swollen Gums", "sym4_d": "Red, puffy, or tender gums indicating active inflammation.",
        "sym5_t": "Surface Stains", "sym5_d": "Discoloration from tea, coffee, wine, or tobacco use.",
        "tech_label": "Modern Hygiene", "tech_title": "Advanced Dental Hygiene", "tech_desc": "We use modern, gentle techniques to ensure your cleaning is both highly effective and comfortable.",
        "t1_t": "Ultrasonic Scalers", "t1_d": "Uses high-frequency vibrations and a cooling water spray to break down tartar quickly.", "t1_m": "Less Scraping",
        "t2_t": "Air Polishing", "t2_d": "A specialized spray of air, water, and fine powder removes surface stains safely.", "t2_m": "Brighter Smile",
        "t3_t": "Fluoride Application", "t3_d": "Topical fluoride varnish applied after cleaning to remineralize and strengthen enamel.", "t3_m": "Cavity Protection",
        "t4_t": "Periodontal Probing", "t4_d": "Careful measurement of gum pockets to monitor your periodontal health over time.", "t4_m": "Early Detection",
        "ban_t": "When Was Your Last Cleaning?", "ban_d": "Dental professionals recommend a professional cleaning every 6 months to maintain optimal oral health.", "ban_c": "Schedule Now",
        "step_l": "Treatment Protocol", "step_t": "The Hygiene Appointment", "step_d": "A comprehensive approach to refreshing your smile.",
        "st1_t": "Examination", "st1_d": "Initial assessment of your gums and teeth for any issues.",
        "st2_t": "Ultrasonic Scaling", "st2_d": "Removal of hard tartar deposits above and below the gumline.",
        "st3_t": "Fine Scaling", "st3_d": "Manual instruments used for precision cleaning in tight spaces.",
        "st4_t": "Polishing", "st4_d": "Smoothing the tooth surfaces and removing superficial stains.",
        "st5_t": "Flossing & Review", "st5_d": "Final flossing and personalized oral hygiene instructions.",
        "ft_t": "Pristine Feeling Guarantee", "ft_d": "Leave our clinic with that incredibly smooth, clean-teeth feeling."
    },
    {
        "id": "teeth-whitening",
        "component_name": "TeethWhitening",
        "breadcrumb": "Teeth Whitening",
        "hero_badge": "Cosmetic Dentistry",
        "hero_title": "Safe In-Office Laser Teeth Whitening",
        "hero_desc": "Gently lift deep tea, coffee, and tobacco stains for a brilliant, photogenic smile without triggering tooth sensitivity or enamel loss.",
        "m1_v": "60m", "m1_l": "Session Time",
        "m2_v": "up to 8", "m2_l": "Shades Whiter",
        "m3_v": "100%", "m3_l": "Enamel Safe",
        "m4_v": "5k+", "m4_l": "Smiles Brightened",
        "cta": "Book Whitening Session",
        "b1": "Laser Activation", "b2": "Desensitizing Gel", "b3": "Instant Results",
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuCA-rUKWmHAWK_DXZAmULQ8ZbrYPDiX90KVTG6MPU4-Q01RMWJ6nEMeTWXFbkJZd9v23rXBbEgAz0zxj7ElDQeXP5W1mhr4p5KnYIRgPw-5Ett5wPettn7t1bDA035BM4W4crSTfzgTU8SxfyQHPB3jBUjpS6ayKI9oUuY5Y93t3c2JPEK8PSSuTg_uxAokuQzVOgvjQB20AlrLKmu2fkNXBDwaurwC0QAPd9MEpF4diEGNDM39tB5ouQ",
        "img_title": "Advanced LED Acceleration", "img_sub": "Faster, Brighter Results", "img_desc": "Our specialized light accelerates the whitening gel, breaking down stains faster.",
        "mini_title": "Immediate Impact", "mini_desc": "Walk out with a brighter smile today",
        "s2_label": "COSMETIC SCIENCE",
        "s2_title": "Understanding Tooth Discoloration",
        "s2_d1": "Over time, the porous nature of tooth enamel absorbs pigments from food, drinks, and tobacco, leading to extrinsic stains. Aging also causes the underlying dentin to darken.",
        "s2_d2": "Professional whitening utilizes active ingredients (like hydrogen or carbamide peroxide) that penetrate the enamel to break apart these complex stain molecules, restoring your tooth's natural brightness.",
        "s2_h_title": "Professional vs. Over-the-Counter",
        "s2_h_desc": "In-office whitening provides controlled, high-concentration gels and protective barriers, ensuring far superior results and safety compared to drugstore kits.",
        "sym_label": "Assessment", "sym_title": "Is Whitening Right For You?",
        "sym1_t": "Dietary Stains", "sym1_d": "Discoloration from heavy consumption of coffee, tea, or red wine.",
        "sym2_t": "Tobacco Stains", "sym2_d": "Yellow or brown staining caused by smoking or chewing tobacco.",
        "sym3_t": "Age-Related Yellowing", "sym3_d": "Natural darkening of teeth as enamel thins and dentin changes with age.",
        "sym4_t": "Special Events", "sym4_d": "Preparing for a wedding, graduation, or important life event.",
        "sym5_t": "Uneven Color", "sym5_d": "General dullness or uneven shading across your smile.",
        "tech_label": "Whitening Technology", "tech_title": "Advanced Brightening Systems", "tech_desc": "We use industry-leading whitening technology designed to maximize results while minimizing sensitivity.",
        "t1_t": "LED Light Acceleration", "t1_d": "A specialized cool blue LED light activates the whitening gel, speeding up the stain-breaking process.", "t1_m": "Faster Results",
        "t2_t": "Desensitizing Agents", "t2_d": "Our gels are formulated with potassium nitrate and fluoride to reduce post-treatment sensitivity.", "t2_m": "Comfortable",
        "t3_t": "Custom Gum Protection", "t3_d": "A resin barrier is carefully applied to your gums to protect them from the whitening agents.", "t3_m": "No Irritation",
        "t4_t": "Take-Home Maintenance", "t4_d": "Custom trays and professional-grade gel for at-home touch-ups to prolong your results.", "t4_m": "Lasting Brightness",
        "ban_t": "Ready for a Brighter Smile?", "ban_d": "Transform your appearance and boost your confidence in just one hour.", "ban_c": "Get a Brighter Smile",
        "step_l": "Treatment Protocol", "step_t": "The Whitening Process", "step_d": "A relaxing, straightforward procedure for immediate results.",
        "st1_t": "Shade Assessment", "st1_d": "Recording your current tooth shade to measure progress.",
        "st2_t": "Preparation & Protection", "st2_d": "Applying protective barriers to your lips and gums.",
        "st3_t": "Gel Application", "st3_d": "Careful application of the professional whitening gel to your teeth.",
        "st4_t": "Light Activation", "st4_d": "The LED light is directed at your teeth for several 15-minute intervals.",
        "st5_t": "Reveal", "st5_d": "The gel is removed, and your new, brighter shade is revealed.",
        "ft_t": "Dazzling Smile Guarantee", "ft_d": "Noticeably whiter teeth after just one appointment."
    },
    {
        "id": "veneers",
        "component_name": "Veneers",
        "breadcrumb": "Veneers",
        "hero_badge": "Smile Makeover",
        "hero_title": "Custom Ceramic Smile Makeovers with Veneers",
        "hero_desc": "Remedy gaps, chips, uneven lengths, and severe discoloration with custom-crafted, ultra-thin ceramic veneers for a perfectly balanced smile.",
        "m1_v": "2-3", "m1_l": "Visits Required",
        "m2_v": "10-15y", "m2_l": "Average Lifespan",
        "m3_v": "100%", "m3_l": "Stain Resistant",
        "m4_v": "2k+", "m4_l": "Veneers Placed",
        "cta": "Design Your Smile",
        "b1": "Ultra-Thin Ceramic", "b2": "Digital Design", "b3": "Minimal Prep",
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuA0ykYLXQ4mq5wBDBzG338XfZFvnh1_jZjLg6asjv_SmR-gYp5iONO4OwLvJm_0W0R7gpba9DezhDqIc-zGkhRCO8L1kSouh2jUo_eRpXnXlWm4Qbl290VbGMMxjjdm0My_GmvHWBv8I_ofl1gmsr7I9HSp00c1wgPws7Q6OsqC0Z61Cx3d-hTMtFCg97yDkzYXaHGoVZrSjqavnVEco2tkuM9sOirPzPHsDpJd7zbuw6fz2EkmTlzK5w",
        "img_title": "Digital Smile Design", "img_sub": "Custom Aesthetics", "img_desc": "Every veneer is meticulously designed using 3D software to match your facial proportions.",
        "mini_title": "Flawless Finish", "mini_desc": "Perfect symmetry and shade",
        "s2_label": "COSMETIC SCIENCE",
        "s2_title": "The Art and Science of Veneers",
        "s2_d1": "Veneers are wafer-thin, custom-made shells of tooth-colored material designed to cover the front surface of teeth. They alter the color, shape, size, or length.",
        "s2_d2": "Crafted from advanced dental porcelain or composite resin, they mimic the light-reflecting properties of natural teeth while offering superior resistance to stains.",
        "s2_h_title": "Conservative Transformation",
        "s2_h_desc": "Unlike crowns, veneers require minimal removal of natural tooth structure, preserving the majority of your healthy enamel.",
        "sym_label": "Assessment", "sym_title": "Are Veneers Right For You?",
        "sym1_t": "Discolored Teeth", "sym1_d": "Stains from root canal treatment, tetracycline, or excess fluoride that resist whitening.",
        "sym2_t": "Worn Down Teeth", "sym2_d": "Teeth that have been naturally worn down over time.",
        "sym3_t": "Chipped or Broken", "sym3_d": "Teeth that have minor chips or structural damage.",
        "sym4_t": "Misaligned or Uneven", "sym4_d": "Teeth that are slightly misaligned, uneven, or irregularly shaped.",
        "sym5_t": "Gaps Between Teeth", "sym5_d": "Diastemas (gaps) that you wish to close without orthodontics.",
        "tech_label": "Smile Design", "tech_title": "Digital Smile Design Technology", "tech_desc": "We use a digital-first approach to plan your smile makeover, ensuring predictable and stunning results.",
        "t1_t": "3D Facial Scanning", "t1_d": "Captures the relationship between your teeth, lips, and facial features for harmony.", "t1_m": "Facial Harmony",
        "t2_t": "Digital Mockups", "t2_d": "See a digital simulation of your proposed new smile before any treatment begins.", "t2_m": "Predictability",
        "t3_t": "E-Max Porcelain", "t3_d": "We use ultra-strong lithium disilicate for veneers that are incredibly thin yet durable.", "t3_m": "Natural Translucency",
        "t4_t": "Trial Smile", "t4_d": "Temporary veneers allow you to 'test drive' your new smile's look and feel.", "t4_m": "Try Before You Buy",
        "ban_t": "Ready for a Smile Makeover?", "ban_d": "Transform your entire appearance with a custom-designed set of porcelain veneers.", "ban_c": "Book Smile Consultation",
        "step_l": "Treatment Protocol", "step_t": "The Veneer Process", "step_d": "A collaborative journey to your perfect smile.",
        "st1_t": "Consultation & Design", "st1_d": "Discussing your goals and taking digital scans to design your new smile.",
        "st2_t": "Preparation", "st2_d": "Minimal reshaping of the enamel to accommodate the veneers.",
        "st3_t": "Temporary Placement", "st3_d": "Placing temporary veneers based on the approved design.",
        "st4_t": "Custom Fabrication", "st4_d": "Your permanent veneers are handcrafted by master ceramists.",
        "st5_t": "Final Bonding", "st5_d": "The final veneers are permanently bonded, adjusted, and polished.",
        "ft_t": "Confidence Guarantee", "ft_d": "A smile you'll be proud to share with the world."
    },
    {
        "id": "wisdom-tooth-removal",
        "component_name": "WisdomToothRemoval",
        "breadcrumb": "Wisdom Tooth Removal",
        "hero_badge": "Oral Surgery",
        "hero_title": "Painless Wisdom Tooth Extraction",
        "hero_desc": "Safe and comfortable removal of impacted or painful wisdom molars with advanced piezoelectric bone surgery, minimizing trauma and healing time.",
        "m1_v": "30-45m", "m1_l": "Procedure Time",
        "m2_v": "0", "m2_l": "Pain Experienced",
        "m3_v": "Fast", "m3_l": "Recovery",
        "m4_v": "8k+", "m4_l": "Extractions",
        "cta": "Schedule Assessment",
        "b1": "Piezoelectric Surgery", "b2": "3D CBCT Planning", "b3": "Conscious Sedation",
        "image_url": "https://lh3.googleusercontent.com/aida/AEtjO1W7q0X9J_mY-Q9d0V1xL_k2P3oY7sN4_q6A8b9M1rT5_xV8u9W2yK1L4p3mO7_t8w8vK5k9bN4g-s8d6",
        "img_title": "Advanced 3D Imaging", "img_sub": "Safe Surgical Planning", "img_desc": "3D CBCT scans precisely locate nerves to ensure completely safe removal.",
        "mini_title": "Quick Recovery", "mini_desc": "Advanced techniques minimize swelling",
        "s2_label": "SURGICAL SCIENCE",
        "s2_title": "Understanding Wisdom Teeth Impaction",
        "s2_d1": "Wisdom teeth, or third molars, often lack sufficient space to erupt properly. This causes them to become 'impacted', growing at incorrect angles and pushing against adjacent teeth.",
        "s2_d2": "Impacted wisdom teeth can lead to pericoronitis (gum infection), decay of the adjacent tooth, cyst formation, and severe jaw pain. Proactive removal is often the safest path.",
        "s2_h_title": "Precision over Force",
        "s2_h_desc": "Modern oral surgery relies on detailed 3D imaging and specialized instruments to remove the tooth atraumatically, preserving surrounding bone.",
        "sym_label": "Assessment", "sym_title": "Signs Your Wisdom Teeth Need Removal",
        "sym1_t": "Jaw Pain", "sym1_d": "Throbbing pain or stiffness in the back of the jaw.",
        "sym2_t": "Swollen Gums", "sym2_d": "Red, tender, or bleeding gums around the back of your mouth.",
        "sym3_t": "Limited Opening", "sym3_d": "Difficulty or pain when trying to open your mouth fully (trismus).",
        "sym4_t": "Bad Breath", "sym4_d": "Persistent bad breath or a bad taste from infection under the gum flap.",
        "sym5_t": "Crowding", "sym5_d": "Feeling pressure as the wisdom tooth pushes your other teeth forward.",
        "tech_label": "Surgical Technology", "tech_title": "Advanced Surgical Protocols", "tech_desc": "We utilize the latest surgical technology to ensure a swift, safe, and comfortable extraction experience.",
        "t1_t": "3D CBCT Scanning", "t1_d": "Provides a 3D view of the tooth roots and their proximity to the inferior alveolar nerve.", "t1_m": "Risk Mitigation",
        "t2_t": "Piezoelectric Surgery", "t2_d": "Uses ultrasonic micro-vibrations to cut bone selectively without damaging soft tissues or nerves.", "t2_m": "Less Trauma",
        "t3_t": "Advanced Anesthesia", "t3_d": "Computer-controlled local anesthesia and optional conscious sedation for a stress-free experience.", "t3_m": "Painless",
        "t4_t": "PRF Therapy", "t4_d": "Platelet-Rich Fibrin, created from your own blood, is placed in the socket to accelerate healing.", "t4_m": "Faster Healing",
        "ban_t": "Experiencing Wisdom Tooth Pain?", "ban_d": "Don't wait for an infection. Get a precise 3D evaluation and painless removal.", "ban_c": "Book Extraction Consult",
        "step_l": "Treatment Protocol", "step_t": "The Extraction Process", "step_d": "A structured approach to safe and comfortable surgery.",
        "st1_t": "3D Diagnostic Scan", "st1_d": "CBCT scan to evaluate the exact position of the tooth and nerves.",
        "st2_t": "Profound Numbing", "st2_d": "Ensuring you are completely numb and comfortable before proceeding.",
        "st3_t": "Atraumatic Access", "st3_d": "Gentle removal of any bone or tissue covering the tooth.",
        "st4_t": "Sectioning & Removal", "st4_d": "The tooth is often divided into smaller pieces for easier, less invasive removal.",
        "st5_t": "Suturing & PRF", "st5_d": "The site is cleaned, PRF is placed, and dissolvable stitches are applied.",
        "ft_t": "Smooth Recovery Guarantee", "ft_d": "Detailed post-op instructions and medications to ensure a fast, comfortable healing phase."
    },
    {
        "id": "pediatric-and-kids-dentistry",
        "component_name": "PediatricDentistry",
        "breadcrumb": "Pediatric & Kids Dentistry",
        "hero_badge": "Children's Care",
        "hero_title": "Stress-Free Pediatric & Kids Dentistry",
        "hero_desc": "Gentle, positive dental care for children, focusing on cavity prevention, fluoride treatments, and establishing lifelong healthy habits.",
        "m1_v": "100%", "m1_l": "Child Friendly",
        "m2_v": "0", "m2_l": "Dental Fear",
        "m3_v": "Early", "m3_l": "Intervention",
        "m4_v": "4k+", "m4_l": "Happy Kids",
        "cta": "Book Child's First Visit",
        "b1": "Preventive Care", "b2": "Painless Techniques", "b3": "Habit Counseling",
        "image_url": "https://lh3.googleusercontent.com/aida-public/AB6AXuCEZ2JBNSW3m-65VaIkzGGJAZpMtOS1IiQdrfWEivRWeXJZJPZkIfKgU7jENySZ3uAbHJ9N5zFXeJTyMt_uDmApSjK73LdbZgsHMgJLA0vCwx3ovMQX9Nxql13gN0cGvWiNCIg54VZ93_5jiVgZ65rSv2T9lqHN5Bi1p5rX9uIiPhqE0Mb9Tsd5Uk2uDdpOkQ3JaHIN8R5Lh63VoRRyzN5xX7_yu3x68-8lhDlA1p9MaS5-y_xBUWq_AQ",
        "img_title": "Child-Centric Environment", "img_sub": "Positive Experiences", "img_desc": "Our clinic is designed to be welcoming and non-intimidating for our youngest patients.",
        "mini_title": "Fun & Educational", "mini_desc": "Teaching good habits early",
        "s2_label": "PEDIATRIC CARE",
        "s2_title": "The Importance of Early Dental Care",
        "s2_d1": "Primary (baby) teeth are crucial for proper chewing, speech development, and guiding permanent teeth into their correct positions.",
        "s2_d2": "Early dental visits help acclimatize children to the dental environment, preventing dental anxiety in the future and allowing us to catch issues like early childhood caries or bite problems.",
        "s2_h_title": "Prevention First",
        "s2_h_desc": "Through sealants and fluoride, we protect vulnerable young teeth from cavities before they even start.",
        "sym_label": "Assessment", "sym_title": "When Should Your Child Visit?",
        "sym1_t": "First Birthday", "sym1_d": "The AAPD recommends a first dental visit by age 1 or when the first tooth appears.",
        "sym2_t": "Tooth Pain", "sym2_d": "Complaints of pain or sensitivity when eating hot, cold, or sweet foods.",
        "sym3_t": "Visible Spots", "sym3_d": "Chalky white, brown, or black spots on the teeth indicating potential decay.",
        "sym4_t": "Prolonged Habits", "sym4_d": "Thumb sucking or pacifier use continuing past age 3.",
        "sym5_t": "Dental Trauma", "sym5_d": "Chipped, broken, or knocked-out teeth from a fall or accident.",
        "tech_label": "Gentle Techniques", "tech_title": "Child-Friendly Dental Approaches", "tech_desc": "We adapt our techniques and terminology to ensure children feel safe, understood, and relaxed.",
        "t1_t": "Tell-Show-Do", "t1_d": "We explain what we will do, demonstrate it, and then perform it, removing fear of the unknown.", "t1_m": "Builds Trust",
        "t2_t": "Pit & Fissure Sealants", "t2_d": "A protective coating applied to the chewing surfaces of molars to prevent cavities.", "t2_m": "Cavity Prevention",
        "t3_t": "Fluoride Varnish", "t3_d": "A quick, painless brush-on treatment that strengthens enamel and reverses early decay.", "t3_m": "Stronger Teeth",
        "t4_t": "Painless Numbing", "t4_d": "Using topical gels and distraction techniques to make necessary treatments virtually painless.", "t4_m": "Tear-Free",
        "ban_t": "Time for Their Checkup?", "ban_d": "Set the foundation for a lifetime of healthy smiles with a fun, positive dental visit.", "ban_c": "Schedule Kids Checkup",
        "step_l": "Treatment Protocol", "step_t": "The Child's First Visit", "step_d": "A gentle introduction to the world of dentistry.",
        "st1_t": "Acclimatization", "st1_d": "A friendly introduction to the dental chair and tools.",
        "st2_t": "Gentle Examination", "st2_d": "A quick, non-invasive check of the teeth, gums, and bite development.",
        "st3_t": "Cleaning & Polishing", "st3_d": "A gentle cleaning to remove plaque and polish the teeth.",
        "st4_t": "Fluoride Treatment", "st4_d": "Application of fluoride varnish to protect against cavities.",
        "st5_t": "Parent Counseling", "st5_d": "Guidance on brushing, diet, and habits for parents.",
        "ft_t": "Happy Smile Guarantee", "ft_d": "A prize and a high-five after every successful visit!"
    }
]

# replacements definition
# original_string : replacement_key
replacements = {
    "RootCanal": "component_name",
    "Root Canal Treatment (RCT)": "breadcrumb",
    "Microscopic Endodontics Protocol": "hero_badge",
    "Single-Sitting Painless Root Canal Treatment (RCT)": "hero_title",
    "Save your natural tooth with high-magnification rotary endodontics, computerized apex locators, and 3D warm vertical obturation. Experience absolute comfort engineered through modern anesthesia.": "hero_desc",
    "85%+": "m1_v",
    "Single Visit Ratio": "m1_l",
    "0%": "m2_v",
    "Discomfort Index": "m2_l",
    "99.9%": "m3_v",
    "Canal Sterilization": "m3_l",
    "15k+": "m4_v",
    "Teeth Preserved": "m4_l",
    "Schedule Pain Relief Visit": "cta",
    "Rubber Dam Sterile Field": "b1",
    "Digital Apex Tracking": "b2",
    "Diode Laser Canal Flush": "b3",
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDPrBc_M2ekCLOrmbEUXBPpZXV0moIblc5unn7wtyDGJAyp4J5Wa5TGwWo1xfSsoV6uOMB-0uoE8qNYIOHge1nx8RZNoix-tmEH4kx5Zmx3DuBXJd-L6iRznG7-QBMzO92sni2kMZHZnLRmiXISo07GKgVccqtWyFJ4Pz2i8L5YsSoHbPfVHlzB6W0yTabHPcD8RyhD3pTPi0ho2DwdGs1U9-j-qRVn2T8SeO0h9M6080Mr3dh-M5qbAQ": "image_url",
    "Carl Zeiss Magna 4K Optics": "img_title",
    "Microscopic Visual Guidance": "img_sub",
    "Enabling our specialists to spot microscopic accessory canal branches invisible to the naked eye.": "img_desc",
    "Painless Guarantee": "mini_title",
    "Gentle computerized target numbing": "mini_desc",
    "ANATOMICAL CONTEXT": "s2_label",
    "Understanding Pulp Infection &amp; Tooth Preservation": "s2_title",
    "Beneath your tooth&apos;s protective outer enamel and hard dentin lies a vital inner core known as the dental pulp. The pulp contains sensitive nerve pathways, blood vessels, and specialized cellular tissue.": "s2_d1",
    "When deep dental decay, hairline micro-fractures, or accidental sports trauma breaches this protective boundary, virulent oral bacteria invade the pulp chamber. Without swift intervention, the infection travels down the apical root canals, triggering abscesses, severe throbbing pain, and permanent jawbone degeneration.": "s2_d2",
    "Preserve vs. Extract": "s2_h_title",
    "Natural teeth retain biological proprioception (chewing sensation) and maintain natural alveolar bone density. Saving your tooth with an RCT is superior and far more economical than extraction and subsequent bridge or implant replacement.": "s2_h_desc",
    "Self Assessment": "sym_label",
    "5 Classic Warning Signs of Pulpal Decay": "sym_title",
    "Spontaneous Throbbing Ache": "sym1_t",
    "Intense, radiating dental pain that frequently worsens at night or while reclining, not relieved by standard over-the-counter painkillers.": "sym1_d",
    "Hot &amp; Cold Sensitivity": "sym2_t",
    "Sharp zinging sensations after drinking hot tea or ice water that linger for more than 15-30 seconds after the temperature stimulus is gone.": "sym2_d",
    "Chewing Tenderness": "sym3_t",
    "Exquisite focal tenderness when applying downward bite pressure or tapping against the tooth, indicating periapical ligament inflammation.": "sym3_d",
    "Gum Swelling &amp; Fistula": "sym4_t",
    "A small pimple-like bump (gum boil) on the adjacent gumline discharging fluid, foul taste, or facial swelling around the jaw.": "sym4_d",
    "Tooth Darkening &amp; Discoloration": "sym5_t",
    "Tooth turning greyish-brown or lifeless compared to adjacent teeth. This occurs as internal necrotic blood products break down inside the internal dentinal tubules.": "sym5_d",
    "Pain-Free Engineering": "tech_label",
    "Next-Generation Endodontic Technology": "tech_title",
    "We have eliminated the anxiety of traditional root canals by integrating digital navigation, ultrasonic bio-activation, and computerized delivery systems.": "tech_desc",
    "Computer-Controlled Anesthesia": "t1_t",
    "Automated microprocessor delivery maintains continuous micro-dosing below the human pain threshold, removing the painful sting of traditional syringes.": "t1_d",
    "Target Numbing": "t1_m",
    "Electronic 6th-Gen Apex Locators": "t2_t",
    "Measures canal length down to 0.1mm accuracy in wet or dry conditions, eliminating radiation exposure from multiple repeated test radiographs.": "t2_d",
    "Sub-Millimeter Exact": "t2_m",
    "Laser &amp; Ultrasonic Canal Flush": "t3_t",
    "Acoustic cavitation agitates disinfecting irrigants into microscopic lateral canals, eradicating 99.9% of biofilms and resistant E. faecalis microbes.": "t3_d",
    "Sterile Disinfection": "t3_m",
    "3D Thermoplastic Bio-Obturation": "t4_t",
    "Warm, liquid bioceramic gutta-percha fills curved and delta canal ramifications seamlessly, forming an impenetrable hermetic seal against future bacteria.": "t4_d",
    "Zero Re-Infection": "t4_m",
    "Can Your RCT Be Done in Just 1 Sitting?": "ban_t",
    "With our rotary apex instrumentation, more than 85% of cases are completed within a single, stress-free 45-minute appointment.": "ban_d",
    "Check Single-Sitting Eligibility": "ban_c",
    "Procedural Workflow": "step_l",
    "The 5-Step RCT Journey": "step_t",
    "Every phase follows stringent international sterilization guidelines to guarantee long-term retention of your tooth.": "step_d",
    "Digital Diagnostics": "st1_t",
    "Ultra-low radiation high-resolution digital X-rays and pulp vitality testing isolate the exact depth of infection and canal curvature.": "st1_d",
    "Isolation &amp; Numbing": "st2_t",
    "Targeted computer anesthesia numbs the tooth completely. A medical-grade latex/nitrile Rubber Dam isolates the tooth from oral bacteria.": "st2_d",
    "Rotary Debridement": "st3_t",
    "Flexible nickel-titanium (NiTi) micro-files glide smoothly along curved root anatomy, sweeping away necrotic pulp tissue painlessly.": "st3_d",
    "Bio-3D Hermetic Fill": "st4_t",
    "The sterilized canal is obturated with biocompatible gutta-percha and antimicrobial bioactive sealer, followed by composite core build-up.": "st4_d",
    "CAD/CAM Zirconia Crown": "st5_t",
    "A 3D optically scanned custom ceramic or zirconia crown is bonded over the tooth, restoring complete chewing strength and natural beauty.": "st5_d",
    "Post-Procedure Comfort Guarantee": "ft_t",
    "Our care concierge monitors your recovery 24 hours post-procedure.": "ft_d"
}

for t in treatments:
    content = template
    for old_str, key in replacements.items():
        if key in t:
            # Need to escape & properly for Hot & Cold etc. if it's already ampersand
            new_str = t[key].replace("&", "&amp;")
            content = content.replace(old_str, new_str)
    
    # Create dir
    dir_path = f"src/app/treatments/{t['id']}"
    os.makedirs(dir_path, exist_ok=True)
    with open(f"{dir_path}/page.tsx", "w") as out:
        out.write(content)

print("Pages created successfully.")
